services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: newjersey
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bon
      MYSQL_PASSWORD: XtNIReUthe%Q0r1#
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - newjersery_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: bon
      DB_PASSWORD: jovi
      DB_NAME: newjersey
    ports:
      - "3000:3000"
    # ALTERAÇÃO: Espera que o serviço 'db' esteja saudável antes de iniciar
    depends_on:
      db:
        condition: service_healthy
    networks:
      - newjersery_network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80" # Porta padrão para HTTP
    depends_on:
      - backend
    networks:
      - newjersery_network

networks:
  newjersery_network:
    driver: bridge

volumes:
  db_data: